description: Duplex Matrix Kscan Driver
compatible: "zmk,kscan-duplex"
include: base.yaml

properties:
  row-gpios:
    type: phandle-array
    required: true
  col-gpios:
    type: phandle-array
    required: true
