CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB_LOGGING=n

CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

# SK6812 (WS2812) LEDサブシステムの有効化（CONFIG_WS2812_STRIP は不要です）
CONFIG_LED_STRIP=y
