CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB_LOGGING=n
CONFIG_KSCAN=y

# D9 / D10 (P0.09 / P0.10) をNFCからGPIOへ強制解放
CONFIG_NFCT_PINS_AS_GPIOS=y

# D6 / D7 (P0.11 / P0.06) のシリアル機能を解除
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
