CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB_LOGGING=n

# 独自Kscanドライバーの有効化
CONFIG_KSCAN=y

# D9/D10ピン (P0.09/P0.10) をNFCからGPIOへ解放
CONFIG_NFCT_PINS_AS_GPIOS=y

# D6/D7ピン (P0.11/P0.06) のUART割り当てを解除
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
